# Generated by Django 5.1.2 on 2024-10-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_eventbooking_booking_details_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventbooking",
            name="cancellation_reason",
        ),
    ]
