# Generated by Django 5.1.2 on 2024-10-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0003_remove_eventbooking_cancellation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventbooking",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
