# Generated by Django 5.1.2 on 2024-10-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_eventbooking_cancellation_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventbooking",
            name="is_cancelled",
            field=models.BooleanField(default=False),
        ),
    ]
